# Generated by Django 3.2.4 on 2021-06-15 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('berth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BayPlanFile',
            fields=[
                ('voy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='berth.voy')),
                ('filename', models.FileField(upload_to='bayplan/%Y/%m/%d/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('ready_to_load', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('updated_filename', models.FileField(blank=True, null=True, upload_to='bayplan/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
