# Generated by Django 3.2.4 on 2021-06-15 11:32

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bayplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargePort',
            fields=[
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('color', colorfield.fields.ColorField(default='#CCFFFF', max_length=18)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('item_no', models.IntegerField()),
                ('container', models.CharField(max_length=11)),
                ('iso_code', models.CharField(blank=True, max_length=4, null=True)),
                ('full', models.BooleanField(default=False)),
                ('partner', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.IntegerField()),
                ('load_port', models.CharField(blank=True, max_length=10, null=True)),
                ('deliverly_port', models.CharField(blank=True, max_length=10, null=True)),
                ('good_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('stowage', models.CharField(max_length=10)),
                ('original_stowage', models.CharField(blank=True, max_length=10, null=True)),
                ('bay', models.CharField(blank=True, max_length=10, null=True)),
                ('original_bay', models.CharField(blank=True, max_length=10, null=True)),
                ('ready_to_load', models.BooleanField(default=False)),
                ('imdg', models.CharField(blank=True, max_length=10, null=True)),
                ('un_no', models.CharField(blank=True, max_length=10, null=True)),
                ('on_deck', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('bayplanfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayplan.bayplanfile')),
                ('dis_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='container.dischargeport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
