# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('berth', '0006_cutoff_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BayPlanFile',
            fields=[
                ('voy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='berth.Voy')),
                ('filename', models.FileField(blank=True, null=True, upload_to='bayplan/%Y/%m/%d/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
