# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayplan', '0002_bayplanfile_ready_to_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayplanfile',
            name='filename',
            field=models.FileField(default=None, upload_to='bayplan/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
