# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayplan', '0003_auto_20180131_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayplanfile',
            name='updated_filename',
            field=models.FileField(blank=True, null=True, upload_to='bayplan/%Y/%m/%d/'),
        ),
    ]
