# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='ready_to_load',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
