# Generated by Django 3.2.4 on 2021-10-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0002_cutoff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoff',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start return Date '),
        ),
    ]
