# Generated by Django 3.2.4 on 2021-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0003_cutoff_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voy',
            options={'permissions': [('change_return_date', 'Can change export start return date')]},
        ),
        migrations.AlterField(
            model_name='voy',
            name='export_cutoff_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Export Return Start Date'),
        ),
    ]
