# Generated by Django 3.2.4 on 2021-12-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0004_auto_20211026_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='callsign',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Call sign'),
        ),
        migrations.AddField(
            model_name='voy',
            name='dis_fross_weight',
            field=models.FloatField(default=0, verbose_name='Discharge gross weight'),
        ),
        migrations.AddField(
            model_name='voy',
            name='load_gross_weight',
            field=models.FloatField(default=0, verbose_name='Load gross weight'),
        ),
    ]
