# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voy',
            name='export_cutoff_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Export Cutoff Date'),
        ),
        migrations.AddField(
            model_name='voy',
            name='imp_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Import Release Date'),
        ),
    ]
