# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0003_reportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='voy',
            name='inverse',
            field=models.BooleanField(default=False, verbose_name='Inverse 180'),
        ),
    ]
