# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('berth', '0004_voy_inverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='cutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_date', models.DateTimeField(blank=True, null=True, verbose_name='Dry CutOff')),
                ('reef_date', models.DateTimeField(blank=True, null=True, verbose_name='Reef CutOff')),
                ('chilled_date', models.DateTimeField(blank=True, null=True, verbose_name='Chilled CutOff')),
                ('durian_date', models.DateTimeField(blank=True, null=True, verbose_name='Durian/Longan CutOff')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='voy',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='voy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berth.Voy'),
        ),
    ]
