# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0005_auto_20171128_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoff',
            name='remark',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
